modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license = "Custom ARR"
issueTrackerURL = "https://github.com/thethirdswan/tfc-food-process-compat/issues"
#clientSideOnly=true #optional - defaults to false if absent
[[mods]]
modId = "tfc_food_compat"
version = "${mod_version}"
displayName = "TFC Food Processing Compat"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tfc-food-processing-compat"
logoFile = "placeholder.png"
credits = "simibubi, vectorwing, EERussianguy"
authors = "The Third Swan"

description = '''
Enables TFC food data preservation when processing TFC foods with other mods!
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="tfcfoodcompat.mixin.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tfc_food_compat]] #optional
    # the modid of the dependency
    modId="neoforge" #mandatory
    # The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    # 'required' requires the mod to exist, 'optional' does not
    # 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
    type="required" #mandatory
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    # The version range of the dependency
    versionRange="[${neo_version},)" #mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.tfc_food_compat]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tfc_food_compat]]
modId = "tfc"
mandatory = true
versionRange = "[4.1.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tfc_food_compat]]
modId = "patchouli"
mandatory = true
versionRange = "[1.21.1-93,)"
ordering = "NONE"
side = "CLIENT"
# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
